POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1yTXVzY2tsZSIsImlkIjoiNWJmMTliYzhlMjdlNmZkNmVlOGY3NTJkIiwiaWF0IjoxNTQyNTY5MjY0fQ.bvV28gLzGV5JizwEXdqt1Zxk3YJm1PlSWmCAZPDy_AM

{
  "title": "Middlewaret kiinnostaa",
  "author": "Makke Middleware",
  "url": "waretus.fi",
  "likes": 69,
  "user": "5bf19bc8e27e6fd6ee8f752d"
}