POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1yTXVzY2tsZSIsImlkIjoiNWJmMTliYzhlMjdlNmZkNmVlOGY3NTJkIiwiaWF0IjoxNTQyNTYxNzAwfQ.5ZW8JtvP9SAgiRMOF81pVIDTFpHm7AlhKkRhpNhJeAE

{
  "title": "Pehmeät arvot",
  "author": "Hentonen",
  "url": "www.fi",
  "likes": 2,
  "user": "5bf19bc8e27e6fd6ee8f752d"
}